# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dennis Tanaka
email: me@dennistanaka.com
description: >- # this means to ignore newlines until "baseurl:"
  Seasoned IT professional with experience in systems analysis and software development. Most recently, I've worked with Golang, Ruby on Rails and Vue in terms of programming tools. I had also the opportunity to experience technologies such as Serverless Computing and Kubernetes. My current goals includes improving my management skills and learning more about DevOps and SRE.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dennistanaka
linkedin_username: dennistanaka
qiita_username: dennistanaka

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  # - portfolio.md
  - blog.md
  - notes.md
  - profile.md

collections:
  notes:
    permalink: "/:collection/:path/"
    output: true

defaults:
- scope:
    path: _notes
    type: notes
  values:
    layout: note
